CREATE DATABASE IF NOT EXISTS PRE_MED CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE PRE_MED;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS AUDIT_LOG, PATIENT_DOCUMENT, DIAGNOSIS, PRESCRIPTION_ITEM, PRESCRIPTION, MEDICATION, LAB_TEST, CONSULTATION, INVOICE, APPOINTMENT, CLINIC_ROOM, SYMPTOM_LOG, VISIT, GUARDIAN, STAFF, PATIENT_INSURANCE, PATIENT, DOCTOR, DEPARTMENT, `USER`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `USER` (
    UserID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(120) NOT NULL,
    Email VARCHAR(190) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE DEPARTMENT (
    DeptID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DeptName VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE DOCTOR (
    UserID INT UNSIGNED PRIMARY KEY,
    DeptID INT UNSIGNED NOT NULL,
    CONSTRAINT fk_doctor_user FOREIGN KEY (UserID) REFERENCES `USER`(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_doctor_department FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
) ENGINE=InnoDB;

CREATE TABLE STAFF (
    UserID INT UNSIGNED PRIMARY KEY,
    DeptID INT UNSIGNED NOT NULL,
    Title VARCHAR(100) NULL,
    CONSTRAINT fk_staff_user FOREIGN KEY (UserID) REFERENCES `USER`(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_staff_department FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
) ENGINE=InnoDB;

CREATE TABLE PATIENT (
    UserID INT UNSIGNED PRIMARY KEY,
    PatientCode VARCHAR(12) NULL UNIQUE,
    AssignedDoctorID INT UNSIGNED NULL,
    RiskLevel ENUM('Low', 'Medium', 'High') NOT NULL DEFAULT 'Low',
    ProfileStatus ENUM('Stable', 'Requires Attention') NOT NULL DEFAULT 'Stable',
    BloodGroup VARCHAR(5) NULL,
    Gender VARCHAR(30) NULL,
    DateOfBirth DATE NULL,
    CONSTRAINT fk_patient_user FOREIGN KEY (UserID) REFERENCES `USER`(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_patient_doctor FOREIGN KEY (AssignedDoctorID) REFERENCES DOCTOR(UserID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE PATIENT_DOCUMENT (
    DocumentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PatientID INT UNSIGNED NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    StoredName VARCHAR(255) NOT NULL,
    MimeType VARCHAR(100) NOT NULL,
    UploadedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_patient FOREIGN KEY (PatientID) REFERENCES PATIENT(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CLINIC_ROOM (
    RoomID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RoomNumber VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE APPOINTMENT (
    AppointmentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    AppointmentDate DATETIME NOT NULL,
    DurationMinutes SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    Status ENUM('Scheduled', 'Confirmed', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Scheduled',
    PatientID INT UNSIGNED NOT NULL,
    DoctorID INT UNSIGNED NOT NULL,
    RoomID INT UNSIGNED NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_doctor_slot (DoctorID, AppointmentDate),
    UNIQUE KEY uq_room_slot (RoomID, AppointmentDate),
    CONSTRAINT chk_appointment_duration CHECK (DurationMinutes BETWEEN 15 AND 240),
    CONSTRAINT fk_appointment_patient FOREIGN KEY (PatientID) REFERENCES PATIENT(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (DoctorID) REFERENCES DOCTOR(UserID),
    CONSTRAINT fk_appointment_room FOREIGN KEY (RoomID) REFERENCES CLINIC_ROOM(RoomID)
) ENGINE=InnoDB;

CREATE TABLE VISIT (
    VisitID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    AdmissionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PatientID INT UNSIGNED NOT NULL,
    CONSTRAINT fk_visit_patient FOREIGN KEY (PatientID) REFERENCES PATIENT(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE SYMPTOM_LOG (
    LogID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PatientID INT UNSIGNED NOT NULL,
    SymptomName VARCHAR(80) NOT NULL DEFAULT 'General',
    SymptomNote TEXT NULL,
    SeverityScore TINYINT UNSIGNED NOT NULL,
    LoggedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_symptom_score CHECK (SeverityScore BETWEEN 1 AND 10),
    CONSTRAINT fk_symptom_patient FOREIGN KEY (PatientID) REFERENCES PATIENT(UserID) ON DELETE CASCADE,
    INDEX idx_symptom_patient_date (PatientID, LoggedAt)
) ENGINE=InnoDB;

CREATE TABLE GUARDIAN (
    PatientID INT UNSIGNED PRIMARY KEY,
    GuardianUserID INT UNSIGNED NOT NULL UNIQUE,
    GuardianName VARCHAR(120) NOT NULL,
    Phone VARCHAR(30) NOT NULL,
    CONSTRAINT fk_guardian_user FOREIGN KEY (GuardianUserID) REFERENCES `USER`(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_guardian_patient FOREIGN KEY (PatientID) REFERENCES PATIENT(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PATIENT_INSURANCE (
    InsuranceID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PatientID INT UNSIGNED NOT NULL,
    CoveragePercentage DECIMAL(5,2) NOT NULL DEFAULT 0,
    ProviderName VARCHAR(120) NULL,
    CONSTRAINT chk_coverage CHECK (CoveragePercentage BETWEEN 0 AND 100),
    CONSTRAINT fk_insurance_patient FOREIGN KEY (PatientID) REFERENCES PATIENT(UserID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CONSULTATION (
    ConsultationID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Notes TEXT NULL,
    VisitID INT UNSIGNED NOT NULL,
    DoctorID INT UNSIGNED NOT NULL,
    Cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_consultation_visit FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID) ON DELETE CASCADE,
    CONSTRAINT fk_consultation_doctor FOREIGN KEY (DoctorID) REFERENCES DOCTOR(UserID)
) ENGINE=InnoDB;

CREATE TABLE LAB_TEST (
    TestID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Result TEXT NULL,
    VisitID INT UNSIGNED NOT NULL,
    Cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_lab_visit FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DIAGNOSIS (
    DiagnosisID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    VisitID INT UNSIGNED NOT NULL,
    DiagnosisText VARCHAR(500) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_diagnosis_visit FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MEDICATION (
    MedicationID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MedicationName VARCHAR(120) NOT NULL UNIQUE,
    StockQuantity INT NOT NULL DEFAULT 0,
    UnitCost DECIMAL(10,2) NOT NULL DEFAULT 0,
    InventoryStatus ENUM('Available', 'Reorder Needed') NOT NULL DEFAULT 'Available'
) ENGINE=InnoDB;

CREATE TABLE PRESCRIPTION (
    PrescriptionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    VisitID INT UNSIGNED NOT NULL,
    PrescribedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prescription_visit FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PRESCRIPTION_ITEM (
    PrescriptionID INT UNSIGNED NOT NULL,
    MedicationID INT UNSIGNED NOT NULL,
    Dosage VARCHAR(120) NOT NULL,
    Quantity INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (PrescriptionID, MedicationID),
    CONSTRAINT fk_item_prescription FOREIGN KEY (PrescriptionID) REFERENCES PRESCRIPTION(PrescriptionID) ON DELETE CASCADE,
    CONSTRAINT fk_item_medication FOREIGN KEY (MedicationID) REFERENCES MEDICATION(MedicationID)
) ENGINE=InnoDB;

CREATE TABLE INVOICE (
    InvoiceID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OutOfPocket DECIMAL(10,2) NOT NULL DEFAULT 0,
    VisitID INT UNSIGNED NOT NULL UNIQUE,
    CONSTRAINT fk_invoice_visit FOREIGN KEY (VisitID) REFERENCES VISIT(VisitID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE AUDIT_LOG (
    AuditID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ActionType VARCHAR(30) NOT NULL,
    TableName VARCHAR(50) NOT NULL,
    RecordID VARCHAR(50) NOT NULL,
    OldData JSON NULL,
    NewData JSON NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID INT UNSIGNED NULL,
    CONSTRAINT fk_audit_user FOREIGN KEY (UserID) REFERENCES `USER`(UserID) ON DELETE SET NULL
) ENGINE=InnoDB;

DELIMITER $$
CREATE TRIGGER symptom_status_after_insert
AFTER INSERT ON SYMPTOM_LOG
FOR EACH ROW
BEGIN
    UPDATE PATIENT
    SET ProfileStatus = CASE WHEN (
        SELECT AVG(SeverityScore) FROM SYMPTOM_LOG WHERE PatientID = NEW.PatientID AND LoggedAt >= DATE_SUB(NOW(), INTERVAL 3 DAY)
    ) >= 7 THEN 'Requires Attention' ELSE 'Stable' END,
        RiskLevel = CASE
            WHEN DateOfBirth IS NOT NULL AND TIMESTAMPDIFF(YEAR, DateOfBirth, CURDATE()) >= 60 AND (SELECT COUNT(*) FROM SYMPTOM_LOG WHERE PatientID = NEW.PatientID AND SeverityScore > 8) >= 2 THEN 'High'
            WHEN (SELECT COUNT(*) FROM SYMPTOM_LOG WHERE PatientID = NEW.PatientID AND SeverityScore >= 7) >= 2 THEN 'Medium'
            ELSE 'Low'
        END
    WHERE UserID = NEW.PatientID;
END$$

CREATE TRIGGER prescription_item_after_insert
AFTER INSERT ON PRESCRIPTION_ITEM
FOR EACH ROW
BEGIN
    IF (SELECT StockQuantity FROM MEDICATION WHERE MedicationID = NEW.MedicationID) < NEW.Quantity THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient medication stock';
    END IF;
    UPDATE MEDICATION
    SET StockQuantity = StockQuantity - NEW.Quantity,
        InventoryStatus = CASE WHEN StockQuantity - NEW.Quantity < 50 THEN 'Reorder Needed' ELSE 'Available' END
    WHERE MedicationID = NEW.MedicationID;
END$$

CREATE TRIGGER diagnosis_or_prescription_update_audit
AFTER UPDATE ON PRESCRIPTION
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (ActionType, TableName, RecordID, OldData, NewData, UserID)
    VALUES ('UPDATE', 'PRESCRIPTION', OLD.PrescriptionID, JSON_OBJECT('VisitID', OLD.VisitID, 'PrescribedAt', OLD.PrescribedAt), JSON_OBJECT('VisitID', NEW.VisitID, 'PrescribedAt', NEW.PrescribedAt), @app_user_id);
END$$

CREATE TRIGGER prescription_delete_audit
AFTER DELETE ON PRESCRIPTION
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (ActionType, TableName, RecordID, OldData, UserID)
    VALUES ('DELETE', 'PRESCRIPTION', OLD.PrescriptionID, JSON_OBJECT('VisitID', OLD.VisitID, 'PrescribedAt', OLD.PrescribedAt), @app_user_id);
END$$

CREATE TRIGGER diagnosis_update_audit
AFTER UPDATE ON DIAGNOSIS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (ActionType, TableName, RecordID, OldData, NewData, UserID)
    VALUES ('UPDATE', 'DIAGNOSIS', OLD.DiagnosisID, JSON_OBJECT('DiagnosisText', OLD.DiagnosisText), JSON_OBJECT('DiagnosisText', NEW.DiagnosisText), @app_user_id);
END$$

CREATE TRIGGER diagnosis_delete_audit
AFTER DELETE ON DIAGNOSIS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (ActionType, TableName, RecordID, OldData, UserID)
    VALUES ('DELETE', 'DIAGNOSIS', OLD.DiagnosisID, JSON_OBJECT('DiagnosisText', OLD.DiagnosisText), @app_user_id);
END$$
DELIMITER ;

INSERT INTO DEPARTMENT (DeptName) VALUES ('Cardiology'), ('Neurology'), ('General Medicine');
INSERT INTO CLINIC_ROOM (RoomNumber) VALUES ('101'), ('102'), ('201');
INSERT INTO MEDICATION (MedicationName, StockQuantity, UnitCost) VALUES ('Amoxicillin', 100, 12.50), ('Metformin', 100, 8.00), ('Lisinopril', 100, 10.00);
